apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-python-app
  labels:
    app: sample-python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-python-app
  template:
    metadata:
      labels:
        app: sample-python-app
    spec:
      containers:
      - name: python-app
        image: python-sample-app-demo:v1 
        volumeMounts: 
        - name: secret-volume
          mountPath: /app/secret
          readOnly: true


        ports:
        - containerPort: 8000
      volumes:
      - name: secret-volume
        secret:
          secretName: test-secret1
